'use client'

import * as React from 'react'
import { Bell, CheckCheck } from 'lucide-react'
import { Badge, Button, Checkbox, EmptyState, cn } from '@appkit/ui'
import { NOTIFICATION_CHANNELS, type NotificationCatalog, type NotificationChannel, type NotificationPreference, type NotificationRecord } from './index'

export type NotificationCenterProps = { items: NotificationRecord[]; catalog: NotificationCatalog; selectedCategory?: string | null; onCategoryChange?: (category: string | null) => void; onOpen?: (item: NotificationRecord) => void; onMarkRead?: (ids: string[] | 'all') => void | Promise<void>; className?: string }

export function NotificationCenter({ items, catalog, selectedCategory = null, onCategoryChange, onOpen, onMarkRead, className }: NotificationCenterProps) {
  const visible = selectedCategory ? items.filter((item) => item.category === selectedCategory) : items
  const unread = items.filter((item) => !item.readAt).length
  return <div className={cn('flex h-full min-h-[34rem] overflow-hidden rounded-lg border border-border bg-surface', className)}><aside className="app-scroll w-64 shrink-0 overflow-y-auto border-r border-border p-3"><button type="button" onClick={() => onCategoryChange?.(null)} className={cn('flex w-full items-center justify-between rounded-md px-3 py-2 text-sm', !selectedCategory ? 'bg-primary-subtle font-medium text-primary' : 'text-fg-muted hover:bg-surface-hover hover:text-fg')}><span>All notifications</span><Badge variant="secondary">{items.length}</Badge></button>{catalog.categories.map((category) => { const count = items.filter((item) => item.category === category.key).length; return <button key={category.key} type="button" onClick={() => onCategoryChange?.(category.key)} className={cn('mt-1 flex w-full items-center justify-between rounded-md px-3 py-2 text-left text-sm', selectedCategory === category.key ? 'bg-primary-subtle font-medium text-primary' : 'text-fg-muted hover:bg-surface-hover hover:text-fg')}><span className="truncate">{category.label}</span>{count ? <span className="text-xs tabular-nums">{count}</span> : null}</button> })}</aside><section className="flex min-w-0 flex-1 flex-col"><header className="flex shrink-0 items-center justify-between border-b border-border px-4 py-3"><div><h2 className="font-semibold text-fg">Notifications</h2><p className="text-xs text-fg-muted">{unread} unread</p></div>{unread && onMarkRead ? <Button variant="outline" size="sm" onClick={() => void onMarkRead('all')}><CheckCheck className="size-4" />Mark all read</Button> : null}</header><div className="app-scroll min-h-0 flex-1 overflow-y-auto">{visible.length ? visible.map((item) => <button key={item.id} type="button" onClick={() => { if (!item.readAt) void onMarkRead?.([item.id]); onOpen?.(item) }} className={cn('flex w-full gap-3 border-b border-border-subtle px-4 py-3 text-left hover:bg-surface-hover', !item.readAt && 'bg-bg-subtle')}><span className={cn('mt-2 size-2 shrink-0 rounded-full', item.readAt ? 'bg-transparent' : item.critical ? 'bg-danger' : 'bg-info')} /><span className="min-w-0 flex-1"><span className="flex items-center gap-2"><span className={cn('truncate text-sm text-fg', !item.readAt && 'font-semibold')}>{item.title}</span>{item.critical ? <Badge variant="destructive">Critical</Badge> : null}</span>{item.body ? <span className="mt-0.5 line-clamp-2 block text-xs text-fg-muted">{item.body}</span> : null}<span className="mt-1 block text-[11px] text-fg-subtle">{new Date(item.occurredAt ?? 0).toLocaleString()}</span></span></button>) : <EmptyState icon={<Bell />} title="You’re all caught up" description="New notifications will appear here." />}</div></section></div>
}

export type NotificationPreferencesProps = { catalog: NotificationCatalog; value: NotificationPreference[]; onChange: (preferences: NotificationPreference[]) => void; availableChannels?: NotificationChannel[]; readOnly?: boolean; className?: string }
export function NotificationPreferences({ catalog, value, onChange, availableChannels = [...NOTIFICATION_CHANNELS], readOnly = false, className }: NotificationPreferencesProps) {
  const enabled = (category: string, channel: NotificationChannel) => value.find((item) => item.category === category && item.channel === channel)?.enabled ?? catalog.categories.find((item) => item.key === category)?.defaultChannels.includes(channel) ?? false
  const update = (category: string, channel: NotificationChannel, next: boolean) => onChange([...value.filter((item) => item.category !== category || item.channel !== channel), { category, channel, enabled: next }])
  const gridStyle = { gridTemplateColumns: `minmax(14rem, 1fr) repeat(${availableChannels.length}, minmax(4.5rem, auto))` }
  return <div className={cn('overflow-x-auto rounded-lg border border-border bg-surface', className)}><div className="min-w-[36rem]"><div style={gridStyle} className="grid border-b border-border bg-bg-subtle px-4 py-2 text-xs font-semibold text-fg-muted"><span>Category</span>{availableChannels.map((channel) => <span key={channel} className="text-center capitalize">{channel.replace('_', ' ')}</span>)}</div>{catalog.categories.map((category) => <div key={category.key} style={gridStyle} className="grid items-center border-b border-border-subtle px-4 py-3 last:border-b-0"><span><span className="block text-sm font-medium text-fg">{category.label}</span>{category.description ? <span className="block text-xs text-fg-muted">{category.description}</span> : null}</span>{availableChannels.map((channel) => <span key={channel} className="flex justify-center"><Checkbox aria-label={`${category.label}: ${channel}`} checked={enabled(category.key, channel)} disabled={readOnly} onChange={(event) => update(category.key, channel, event.currentTarget.checked)} /></span>)}</div>)}</div></div>
}
